#私有索引库
source ‘https://github.com/icpmobile/ICPMSpecs.git’
#CocoaPods 公共索引库
source ‘https://github.com/CocoaPods/Specs.git’

use_frameworks!

platform :ios, '9.0'

target 'HTUIKit_Example' do
  pod 'HTUIKit', :path => '../'

  target 'HTUIKit_Tests' do
    inherit! :search_paths

    
  end
end
